# Generated by Django 3.0.7 on 2020-07-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='autor',
            new_name='author',
        ),
    ]
