# Generated by Django 3.0.7 on 2020-07-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
