# Generated by Django 3.0.7 on 2020-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=12, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
